# Cargo config file

# Environment variables for all 'cargo ...' commands
[env]

# Scope down tracing 
RUST_LOG = "tracklists=debug"

# -- Service Environment Variables
# In deployment, should be managed by container
#
# # Config Map

SERVICE_TEMPLATES = "templates/"
